version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spot95
    ports:
      - "5432:5432"
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - db
      - cache
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "5173:5173"
